### ISSUE TITLE
Does not Install

### ISSUE THREAD

**Issue by zmarric** [jjosephy/interview#1]
This does not install when you run " docker build . "
This is the error given:

> Step 9 : RUN go install github.com/jjosephy/go/interview
>  ---> Running in 703041f4de0d
> src/github.com/jjosephy/go/interview/main.go:5:5: cannot find package "github.com/jjosephy/interview/authentication" in any of:
>   /usr/local/go/src/github.com/jjosephy/interview/authentication (from $GOROOT)
>   /go/src/github.com/jjosephy/interview/authentication (from $GOPATH)
> src/github.com/jjosephy/go/interview/main.go:6:5: cannot find package "github.com/jjosephy/interview/handler" in any of:
>   /usr/local/go/src/github.com/jjosephy/interview/handler (from $GOROOT)
>   /go/src/github.com/jjosephy/interview/handler (from $GOPATH)
> src/github.com/jjosephy/go/interview/main.go:7:5: cannot find package "github.com/jjosephy/interview/repository" in any of:
>   /usr/local/go/src/github.com/jjosephy/interview/repository (from $GOROOT)
>   /go/src/github.com/jjosephy/interview/repository (from $GOPATH)

**Comment by jjosephy** [comment]
Hmm what happens when u run go get at cmd line first does it install locally?

**Comment by zmarric** [comment]
you have to update the jwttokenprovider you have to use the MyTimeClaims struct w/ StandardClaims. w/o it your code does not run. it changed to an interface. 

https://github.com/dgrijalva/jwt-go/issues/141 explains the issues.

**Comment by jjosephy** [comment]
Fixed with change from zmarric
